package modelold;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reponse generated by hbm2java
 */
@Entity
@Table(name = "reponse", catalog = "wrc")
//@Table(name = "reponse", catalog = "u575564338_wrc")
public class Reponse implements java.io.Serializable, Comparable{

	private Integer idReponse;
	private Question question;
	private String descriptionReponse;
	private Boolean isBonneReponse;
	private Integer valeurReponse;
	private Set<ReponseApprenantExamen> reponseApprenantExamens = new HashSet<ReponseApprenantExamen>(0);
	private Set<ReponseApprenant> reponseApprenants = new HashSet<ReponseApprenant>(0);

	public Reponse() {
	}

	public Reponse(Question question, String descriptionReponse, Boolean isBonneReponse, Integer valeurReponse,
			Set<ReponseApprenantExamen> reponseApprenantExamens, Set<ReponseApprenant> reponseApprenants) {
		this.question = question;
		this.descriptionReponse = descriptionReponse;
		this.isBonneReponse = isBonneReponse;
		this.valeurReponse = valeurReponse;
		this.reponseApprenantExamens = reponseApprenantExamens;
		this.reponseApprenants = reponseApprenants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_reponse", unique = true, nullable = false)
	public Integer getIdReponse() {
		return this.idReponse;
	}

	public void setIdReponse(Integer idReponse) {
		this.idReponse = idReponse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_question")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "description_reponse", length = 500)
	public String getDescriptionReponse() {
		return this.descriptionReponse;
	}

	public void setDescriptionReponse(String descriptionReponse) {
		this.descriptionReponse = descriptionReponse;
	}

	@Column(name = "is_bonne_reponse")
	public Boolean getIsBonneReponse() {
		return this.isBonneReponse;
	}

	public void setIsBonneReponse(Boolean isBonneReponse) {
		this.isBonneReponse = isBonneReponse;
	}

	@Column(name = "valeur_reponse")
	public Integer getValeurReponse() {
		return this.valeurReponse;
	}

	public void setValeurReponse(Integer valeurReponse) {
		this.valeurReponse = valeurReponse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reponse")
	public Set<ReponseApprenantExamen> getReponseApprenantExamens() {
		return this.reponseApprenantExamens;
	}

	public void setReponseApprenantExamens(Set<ReponseApprenantExamen> reponseApprenantExamens) {
		this.reponseApprenantExamens = reponseApprenantExamens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reponse")
	public Set<ReponseApprenant> getReponseApprenants() {
		return this.reponseApprenants;
	}

	public void setReponseApprenants(Set<ReponseApprenant> reponseApprenants) {
		this.reponseApprenants = reponseApprenants;
	}

	@Override
	public String toString() {
		return "Reponse [idReponse=" + idReponse + ", question=" + question.getIdQuestion() + ", descriptionReponse="
				+ descriptionReponse + ", isBonneReponse=" + isBonneReponse + "]";
	}

	@Override
	public int compareTo(Object o) {
		int compareindex =((Reponse)o).getIdReponse();
		return this.idReponse-compareindex;
	}
	
	

}