package modelold;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResultatExamen generated by hbm2java
 */
@Entity
@Table(name = "resultat_examen", catalog = "wrc")
//@Table(name = "resultat_examen", catalog = "u575564338_wrc")
public class ResultatExamen implements java.io.Serializable {

	private Integer idResultatExamen;
	private Apprenant apprenant;
	private Examen examen;
	private Double note;
	private Boolean absenceJustifie;

	public ResultatExamen() {
	}

	public ResultatExamen(Apprenant apprenant, Examen examen, Double note, Boolean absenceJustifie) {
		this.apprenant = apprenant;
		this.examen = examen;
		this.note = note;
		this.absenceJustifie = absenceJustifie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_resultat_examen", unique = true, nullable = false)
	public Integer getIdResultatExamen() {
		return this.idResultatExamen;
	}

	public void setIdResultatExamen(Integer idResultatExamen) {
		this.idResultatExamen = idResultatExamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_apprenant")
	public Apprenant getApprenant() {
		return this.apprenant;
	}

	public void setApprenant(Apprenant apprenant) {
		this.apprenant = apprenant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_examen")
	public Examen getExamen() {
		return this.examen;
	}

	public void setExamen(Examen examen) {
		this.examen = examen;
	}

	@Column(name = "note", precision = 22, scale = 0)
	public Double getNote() {
		return this.note;
	}

	public void setNote(Double note) {
		this.note = note;
	}

	@Column(name = "absence_justifie")
	public Boolean getAbsenceJustifie() {
		return this.absenceJustifie;
	}

	public void setAbsenceJustifie(Boolean absenceJustifie) {
		this.absenceJustifie = absenceJustifie;
	}

}