package dto;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "examen", catalog = "evaly")
public class ExamenDto implements java.io.Serializable {

	private Integer idExamen;
	private Integer formateur;
	private String titre;
	private Integer promotion;
	private Integer sujet;
	private String dateExamen;
	private Integer dureeExamen;


	public ExamenDto() {
	}


	public Integer getIdExamen() {
		return this.idExamen;
	}

	public void setIdExamen(Integer idExamen) {
		this.idExamen = idExamen;
	}

	public Integer getFormateur() {
		return this.formateur;
	}

	public void setFormateur(Integer formateur) {
		this.formateur = formateur;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getDateExamen() {
		return this.dateExamen;
	}

	public void setDateExamen(String dateExamen) {
		this.dateExamen = dateExamen;
	}

	public Integer getDureeExamen() {
		return this.dureeExamen;
	}

	public void setDureeExamen(Integer dureeExamen) {
		this.dureeExamen = dureeExamen;
	}


	public Integer getPromotion() {
		return promotion;
	}


	public void setPromotion(Integer promotion) {
		this.promotion = promotion;
	}


	public Integer getSujet() {
		return sujet;
	}


	public void setSujet(Integer sujet) {
		this.sujet = sujet;
	}


	@Override
	public String toString() {
		return "ExamenDto [idExamen=" + idExamen + ", formateur=" + formateur + ", titre=" + titre + ", promotion="
				+ promotion + ", sujet=" + sujet + ", dateExamen=" + dateExamen + ", dureeExamen=" + dureeExamen + "]";
	}





}