package dto;
// Generated 26 mars 2021 ï¿½ 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Entity;
import javax.persistence.Table;

import modelold.Question;
import modelold.Reponse;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "wrc")
public class QuestionDto implements java.io.Serializable, Comparable {

	private Integer idQuestion;
	private Integer theme;

	private Integer idMatiere;
	private String nvtheme;
	private String nvthemebool;

	private String descriptionQuestion;
	private Integer coefficient;
	private Boolean isQcm;
	private double tauxreussite;
	private Integer nbnotes;
	private Integer rep1id;
	private Integer rep2id;
	private Integer rep3id;
	private Integer rep4id;
	private String rep1;
	private String rep2;
	private String rep3;
	private String rep4;
	private String rep1br;
	private String rep2br;
	private String rep3br;
	private String rep4br;
	private Boolean rep1bool;
	private Boolean rep2bool;
	private Boolean rep3bool;
	private Boolean rep4bool;
	private Boolean isVrai;
	private Boolean toReset;

	public QuestionDto() {
	}

	public QuestionDto(Question q) {

		for (Reponse r : q.reponsesArray()) {
			System.out.println(r);
		}

		this.idQuestion = q.getIdQuestion();
		this.theme = q.getTheme().getIdTheme();
		this.idMatiere = q.getTheme().getMatiere().getIdMatiere();

		this.descriptionQuestion = q.getDescriptionQuestion();
		this.coefficient = q.getCoefficient();
		this.isQcm = q.getIsQcm();
		this.tauxreussite = q.getTauxreussite();
		this.nbnotes = q.getNbnotes();

		this.rep1id = q.reponsesArray().get(0).getIdReponse();
		this.rep1 = q.reponsesArray().get(0).getDescriptionReponse();
		if (q.reponsesArray().get(0).getIsBonneReponse() != null)
			this.rep1bool = q.reponsesArray().get(0).getIsBonneReponse();

		if (q.reponsesArray().size() > 1) {
			this.rep2id = q.reponsesArray().get(1).getIdReponse();
			this.rep2 = q.reponsesArray().get(1).getDescriptionReponse();
			if (q.reponsesArray().get(1).getIsBonneReponse() != null)
				this.rep2bool = q.reponsesArray().get(1).getIsBonneReponse();
		}
		if (q.reponsesArray().size() > 2) {
			this.rep3id = q.reponsesArray().get(2).getIdReponse();
			this.rep3 = q.reponsesArray().get(2).getDescriptionReponse();
			if (q.reponsesArray().get(2).getIsBonneReponse() != null)
				this.rep3bool = q.reponsesArray().get(2).getIsBonneReponse();
		}
		if (q.reponsesArray().size() > 3) {
			this.rep4id = q.reponsesArray().get(3).getIdReponse();
			this.rep4 = q.reponsesArray().get(3).getDescriptionReponse();
			if (q.reponsesArray().get(3).getIsBonneReponse() != null)
				this.rep4bool = q.reponsesArray().get(3).getIsBonneReponse();
		}
	}

	public String getNvthemebool() {
		return nvthemebool;
	}

	public void setNvthemebool(String nvthemebool) {
		this.nvthemebool = nvthemebool;
	}

	public Integer getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(Integer idQuestion) {
		this.idQuestion = idQuestion;
	}

	public Integer getTheme() {
		return this.theme;
	}

	public void setTheme(Integer theme) {
		this.theme = theme;
	}

	public String getDescriptionQuestion() {
		return this.descriptionQuestion;
	}

	public void setDescriptionQuestion(String descriptionQuestion) {
		this.descriptionQuestion = descriptionQuestion;
	}

	public Integer getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(Integer coefficient) {
		this.coefficient = coefficient;
	}

	public Boolean getIsQcm() {
		return this.isQcm;
	}

	public void setIsQcm(Boolean isQcm) {
		this.isQcm = isQcm;
	}

	public double getTauxreussite() {
		return tauxreussite;
	}

	public void setTauxreussite(double tauxreussite) {
		this.tauxreussite = tauxreussite;
	}

	public Integer getNbnotes() {
		return nbnotes;
	}

	public void setNbnotes(Integer nbnotes) {
		this.nbnotes = nbnotes;
	}

	public String getRep1() {
		return rep1;
	}

	public void setRep1(String rep1) {
		this.rep1 = rep1;
	}

	public String getRep2() {
		return rep2;
	}

	public void setRep2(String rep2) {
		this.rep2 = rep2;
	}

	public String getRep3() {
		return rep3;
	}

	public void setRep3(String rep3) {
		this.rep3 = rep3;
	}

	public String getRep4() {
		return rep4;
	}

	public void setRep4(String rep4) {
		this.rep4 = rep4;
	}

	public Boolean getIsVrai() {
		return isVrai;
	}

	public void setIsVrai(Boolean isVrai) {
		this.isVrai = isVrai;
	}

	public Integer getIdMatiere() {
		return idMatiere;
	}

	public void setIdMatiere(Integer idMatiere) {
		this.idMatiere = idMatiere;
	}

	public String getNvtheme() {
		return nvtheme;
	}

	public void setNvtheme(String nvtheme) {
		this.nvtheme = nvtheme;
	}

	public String getRep1br() {
		return rep1br;
	}

	public void setRep1br(String rep1br) {
		this.rep1br = rep1br;
	}

	public String getRep2br() {
		return rep2br;
	}

	public void setRep2br(String rep2br) {
		this.rep2br = rep2br;
	}

	public String getRep3br() {
		return rep3br;
	}

	public void setRep3br(String rep3br) {
		this.rep3br = rep3br;
	}

	public String getRep4br() {
		return rep4br;
	}

	public void setRep4br(String rep4br) {
		this.rep4br = rep4br;
	}

	public Boolean getToReset() {
		return toReset;
	}

	public void setToReset(Boolean toReset) {
		this.toReset = toReset;
	}

	@Override
	public int compareTo(Object o) {
		int compare = ((QuestionDto) o).getIdQuestion();
		return this.idQuestion - compare;
	}

	public Integer getRep1id() {
		return rep1id;
	}

	public void setRep1id(Integer rep1id) {
		this.rep1id = rep1id;
	}

	public Integer getRep2id() {
		return rep2id;
	}

	public void setRep2id(Integer rep2id) {
		this.rep2id = rep2id;
	}

	public Integer getRep3id() {
		return rep3id;
	}

	public void setRep3id(Integer rep3id) {
		this.rep3id = rep3id;
	}

	public Integer getRep4id() {
		return rep4id;
	}

	public void setRep4id(Integer rep4id) {
		this.rep4id = rep4id;
	}

	public Boolean getRep1bool() {
		return rep1bool;
	}

	public void setRep1bool(Boolean rep1bool) {
		this.rep1bool = rep1bool;
	}

	public Boolean getRep2bool() {
		return rep2bool;
	}

	public void setRep2bool(Boolean rep2bool) {
		this.rep2bool = rep2bool;
	}

	public Boolean getRep3bool() {
		return rep3bool;
	}

	public void setRep3bool(Boolean rep3bool) {
		this.rep3bool = rep3bool;
	}

	public Boolean getRep4bool() {
		return rep4bool;
	}

	public void setRep4bool(Boolean rep4bool) {
		this.rep4bool = rep4bool;
	}

}