package dto;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

import modelold.Examen;
import modelold.Question;
import modelold.SujetQuestion;

/**
 * Sujet generated by hbm2java
 */

public class QuestionnaireDto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8379509563443107046L;
	private Integer idExamen;
	private Integer idSujet;
	private Integer formateur;
	private String titre;
	private String nomSujet;
	private String descriptionSujet;
	private ArrayList<QuestionDto> questions = new ArrayList<QuestionDto>();
	

	public QuestionnaireDto() {
	}

	public QuestionnaireDto(Examen ex) {
		this.idExamen = ex.getIdExamen();
		this.idSujet = ex.getSujet().getIdSujet();
		this.formateur = ex.getFormateur().getId();
		this.titre = ex.getTitre();
		this.nomSujet = ex.getSujet().getNom();
		this.descriptionSujet = ex.getSujet().getdescriptionSujet();
	}

	public Integer getIdExamen() {
		return idExamen;
	}

	public void setIdExamen(Integer idExamen) {
		this.idExamen = idExamen;
	}

	public Integer getIdSujet() {
		return idSujet;
	}

	public void setIdSujet(Integer idSujet) {
		this.idSujet = idSujet;
	}

	public Integer getFormateur() {
		return formateur;
	}

	public void setFormateur(Integer formateur) {
		this.formateur = formateur;
	}

	public String getTitre() {
		return titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getNomSujet() {
		return nomSujet;
	}

	public void setNomSujet(String nomSujet) {
		this.nomSujet = nomSujet;
	}

	public String getDescriptionSujet() {
		return descriptionSujet;
	}

	public void setDescriptionSujet(String descriptionSujet) {
		this.descriptionSujet = descriptionSujet;
	}

	public ArrayList<QuestionDto> getQuestions() {
		return questions;
	}

	@SuppressWarnings("unchecked")
	public void setQuestions(ArrayList<QuestionDto> questions) {
		this.questions = questions;
	}

	@SuppressWarnings("unchecked")
	public void questionsExam(Examen exam) {
		ArrayList<QuestionDto> questionstemp = new ArrayList<QuestionDto>();
		Set<SujetQuestion> sujetQuestions = exam.getSujet().getSujetQuestions();
		for (SujetQuestion sq : sujetQuestions) {
			System.out.println(sq.getQuestion());
			questionstemp.add(new QuestionDto(sq.getQuestion()));
		}
		Collections.sort(questionstemp);
		this.questions=questionstemp;
	}
	
	public static ArrayList<QuestionDto> questionsExamReturn(Examen exam) {
		ArrayList<QuestionDto> questionstemp = new ArrayList<QuestionDto>();
		Set<SujetQuestion> sujetQuestions = exam.getSujet().getSujetQuestions();
		for (SujetQuestion sq : sujetQuestions) {
			System.out.println(sq.getQuestion());
			questionstemp.add(new QuestionDto(sq.getQuestion()));
		}
		Collections.sort(questionstemp);
		return questionstemp;
	}

	@Override
	public String toString() {
		return "QuestionnaireDto [idExamen=" + idExamen + ", idSujet=" + idSujet + ", formateur=" + formateur
				+ ", titre=" + titre + ", nomSujet=" + nomSujet + ", descriptionSujet=" + descriptionSujet + "]";
	}
	
	

}