package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "wrc")
public class Categorie implements java.io.Serializable {

	private int id;
	private String nom;
	private Set<ChampionnatCategorie> championnatCategories = new HashSet<ChampionnatCategorie>(0);
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);
	private Set<CategorieVehicule> categorieVehicules = new HashSet<CategorieVehicule>(0);

	public Categorie() {
	}

	public Categorie(int id, String nom) {
		this.id = id;
		this.nom = nom;
	}

	public Categorie(int id, String nom, Set<ChampionnatCategorie> championnatCategories, Set<Vehicule> vehicules,
			Set<CategorieVehicule> categorieVehicules) {
		this.id = id;
		this.nom = nom;
		this.championnatCategories = championnatCategories;
		this.vehicules = vehicules;
		this.categorieVehicules = categorieVehicules;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<ChampionnatCategorie> getChampionnatCategories() {
		return this.championnatCategories;
	}

	public void setChampionnatCategories(Set<ChampionnatCategorie> championnatCategories) {
		this.championnatCategories = championnatCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<CategorieVehicule> getCategorieVehicules() {
		return this.categorieVehicules;
	}

	public void setCategorieVehicules(Set<CategorieVehicule> categorieVehicules) {
		this.categorieVehicules = categorieVehicules;
	}

}
