package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategorieVehicule generated by hbm2java
 */
@Entity
@Table(name = "categorie_vehicule", catalog = "wrc")
public class CategorieVehicule implements java.io.Serializable {

	private CategorieVehiculeId id;
	private Categorie categorie;
	private Vehicule vehicule;

	public CategorieVehicule() {
	}

	public CategorieVehicule(CategorieVehiculeId id) {
		this.id = id;
	}

	public CategorieVehicule(CategorieVehiculeId id, Categorie categorie, Vehicule vehicule) {
		this.id = id;
		this.categorie = categorie;
		this.vehicule = vehicule;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idCategorie", column = @Column(name = "idCategorie")),
			@AttributeOverride(name = "idVehicule", column = @Column(name = "idVehicule")) })
	public CategorieVehiculeId getId() {
		return this.id;
	}

	public void setId(CategorieVehiculeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategorie", insertable = false, updatable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVehicule", insertable = false, updatable = false)
	public Vehicule getVehicule() {
		return this.vehicule;
	}

	public void setVehicule(Vehicule vehicule) {
		this.vehicule = vehicule;
	}

}
