package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategorieVehiculeId generated by hbm2java
 */
@Embeddable
public class CategorieVehiculeId implements java.io.Serializable {

	private Integer idCategorie;
	private Integer idVehicule;

	public CategorieVehiculeId() {
	}

	public CategorieVehiculeId(Integer idCategorie, Integer idVehicule) {
		this.idCategorie = idCategorie;
		this.idVehicule = idVehicule;
	}

	@Column(name = "idCategorie")
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "idVehicule")
	public Integer getIdVehicule() {
		return this.idVehicule;
	}

	public void setIdVehicule(Integer idVehicule) {
		this.idVehicule = idVehicule;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategorieVehiculeId))
			return false;
		CategorieVehiculeId castOther = (CategorieVehiculeId) other;

		return ((this.getIdCategorie() == castOther.getIdCategorie()) || (this.getIdCategorie() != null
				&& castOther.getIdCategorie() != null && this.getIdCategorie().equals(castOther.getIdCategorie())))
				&& ((this.getIdVehicule() == castOther.getIdVehicule())
						|| (this.getIdVehicule() != null && castOther.getIdVehicule() != null
								&& this.getIdVehicule().equals(castOther.getIdVehicule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCategorie() == null ? 0 : this.getIdCategorie().hashCode());
		result = 37 * result + (getIdVehicule() == null ? 0 : this.getIdVehicule().hashCode());
		return result;
	}

}
