package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChampionnatCategorieId generated by hbm2java
 */
@Embeddable
public class ChampionnatCategorieId implements java.io.Serializable {

	private int idChampionnat;
	private int idCategorie;

	public ChampionnatCategorieId() {
	}

	public ChampionnatCategorieId(int idChampionnat, int idCategorie) {
		this.idChampionnat = idChampionnat;
		this.idCategorie = idCategorie;
	}

	@Column(name = "idChampionnat", nullable = false)
	public int getIdChampionnat() {
		return this.idChampionnat;
	}

	public void setIdChampionnat(int idChampionnat) {
		this.idChampionnat = idChampionnat;
	}

	@Column(name = "idCategorie", nullable = false)
	public int getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(int idCategorie) {
		this.idCategorie = idCategorie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChampionnatCategorieId))
			return false;
		ChampionnatCategorieId castOther = (ChampionnatCategorieId) other;

		return (this.getIdChampionnat() == castOther.getIdChampionnat())
				&& (this.getIdCategorie() == castOther.getIdCategorie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdChampionnat();
		result = 37 * result + this.getIdCategorie();
		return result;
	}

}
