package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChampionnatEpreuveId generated by hbm2java
 */
@Embeddable
public class ChampionnatEpreuveId implements java.io.Serializable {

	private Integer idChampionnat;
	private Integer idEpreuve;

	public ChampionnatEpreuveId() {
	}

	public ChampionnatEpreuveId(Integer idChampionnat, Integer idEpreuve) {
		this.idChampionnat = idChampionnat;
		this.idEpreuve = idEpreuve;
	}

	@Column(name = "idChampionnat")
	public Integer getIdChampionnat() {
		return this.idChampionnat;
	}

	public void setIdChampionnat(Integer idChampionnat) {
		this.idChampionnat = idChampionnat;
	}

	@Column(name = "idEpreuve")
	public Integer getIdEpreuve() {
		return this.idEpreuve;
	}

	public void setIdEpreuve(Integer idEpreuve) {
		this.idEpreuve = idEpreuve;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChampionnatEpreuveId))
			return false;
		ChampionnatEpreuveId castOther = (ChampionnatEpreuveId) other;

		return ((this.getIdChampionnat() == castOther.getIdChampionnat())
				|| (this.getIdChampionnat() != null && castOther.getIdChampionnat() != null
						&& this.getIdChampionnat().equals(castOther.getIdChampionnat())))
				&& ((this.getIdEpreuve() == castOther.getIdEpreuve()) || (this.getIdEpreuve() != null
						&& castOther.getIdEpreuve() != null && this.getIdEpreuve().equals(castOther.getIdEpreuve())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdChampionnat() == null ? 0 : this.getIdChampionnat().hashCode());
		result = 37 * result + (getIdEpreuve() == null ? 0 : this.getIdEpreuve().hashCode());
		return result;
	}

}
