package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChampionnatEpreuve generated by hbm2java
 */
@Entity
@Table(name = "championnat_epreuve", catalog = "wrc")
public class ChampionnatEpreuve implements java.io.Serializable {

	private ChampionnatEpreuveId id;

	public ChampionnatEpreuve() {
	}

	public ChampionnatEpreuve(ChampionnatEpreuveId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idChampionnat", column = @Column(name = "idChampionnat")),
			@AttributeOverride(name = "idEpreuve", column = @Column(name = "idEpreuve")) })
	public ChampionnatEpreuveId getId() {
		return this.id;
	}

	public void setId(ChampionnatEpreuveId id) {
		this.id = id;
	}

}
