package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChampionnatCategorie generated by hbm2java
 */
@Entity
@Table(name = "championnat_categorie", catalog = "wrc")
public class ChampionnatCategorie implements java.io.Serializable {

	private ChampionnatCategorieId id;
	private Categorie categorie;
	private Championnat championnat;

	public ChampionnatCategorie() {
	}

	public ChampionnatCategorie(ChampionnatCategorieId id, Categorie categorie, Championnat championnat) {
		this.id = id;
		this.categorie = categorie;
		this.championnat = championnat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idChampionnat", column = @Column(name = "idChampionnat", nullable = false)),
			@AttributeOverride(name = "idCategorie", column = @Column(name = "idCategorie", nullable = false)) })
	public ChampionnatCategorieId getId() {
		return this.id;
	}

	public void setId(ChampionnatCategorieId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategorie", nullable = false, insertable = false, updatable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChampionnat", nullable = false, insertable = false, updatable = false)
	public Championnat getChampionnat() {
		return this.championnat;
	}

	public void setChampionnat(Championnat championnat) {
		this.championnat = championnat;
	}

}
