package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Championnat generated by hbm2java
 */
@Entity
@Table(name = "championnat", catalog = "wrc")
public class Championnat implements java.io.Serializable {

	private int id;
	private Utilisateur utilisateur;
	private String nom;
	private String degradation;
	private Boolean degatsExtremes;
	private Byte powerstage;
	private String pointsPowerstage;
	private String pointsEpreuve;
	private String reglePoint;
	private Set<EquipeChampionnat> equipeChampionnats = new HashSet<EquipeChampionnat>(0);
	private Set<ResultatEpreuve> resultatEpreuves = new HashSet<ResultatEpreuve>(0);
	private Set<ChampionnatCategorie> championnatCategories = new HashSet<ChampionnatCategorie>(0);
	private Set<ResultatChampionnat> resultatChampionnats = new HashSet<ResultatChampionnat>(0);
	private Set<Chapeau> chapeaus = new HashSet<Chapeau>(0);

	public Championnat() {
	}

	public Championnat(int id, Utilisateur utilisateur, String nom) {
		this.id = id;
		this.utilisateur = utilisateur;
		this.nom = nom;
	}

	public Championnat(int id, Utilisateur utilisateur, String nom, String degradation, Boolean degatsExtremes,
			Byte powerstage, String pointsPowerstage, String pointsEpreuve, String reglePoint,
			Set<EquipeChampionnat> equipeChampionnats, Set<ResultatEpreuve> resultatEpreuves,
			Set<ChampionnatCategorie> championnatCategories, Set<ResultatChampionnat> resultatChampionnats,
			Set<Chapeau> chapeaus) {
		this.id = id;
		this.utilisateur = utilisateur;
		this.nom = nom;
		this.degradation = degradation;
		this.degatsExtremes = degatsExtremes;
		this.powerstage = powerstage;
		this.pointsPowerstage = pointsPowerstage;
		this.pointsEpreuve = pointsEpreuve;
		this.reglePoint = reglePoint;
		this.equipeChampionnats = equipeChampionnats;
		this.resultatEpreuves = resultatEpreuves;
		this.championnatCategories = championnatCategories;
		this.resultatChampionnats = resultatChampionnats;
		this.chapeaus = chapeaus;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCreateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "degradation", length = 8)
	public String getDegradation() {
		return this.degradation;
	}

	public void setDegradation(String degradation) {
		this.degradation = degradation;
	}

	@Column(name = "degatsExtremes")
	public Boolean getDegatsExtremes() {
		return this.degatsExtremes;
	}

	public void setDegatsExtremes(Boolean degatsExtremes) {
		this.degatsExtremes = degatsExtremes;
	}

	@Column(name = "powerstage")
	public Byte getPowerstage() {
		return this.powerstage;
	}

	public void setPowerstage(Byte powerstage) {
		this.powerstage = powerstage;
	}

	@Column(name = "pointsPowerstage", length = 200)
	public String getPointsPowerstage() {
		return this.pointsPowerstage;
	}

	public void setPointsPowerstage(String pointsPowerstage) {
		this.pointsPowerstage = pointsPowerstage;
	}

	@Column(name = "pointsEpreuve", length = 200)
	public String getPointsEpreuve() {
		return this.pointsEpreuve;
	}

	public void setPointsEpreuve(String pointsEpreuve) {
		this.pointsEpreuve = pointsEpreuve;
	}

	@Column(name = "reglePoint", length = 200)
	public String getReglePoint() {
		return this.reglePoint;
	}

	public void setReglePoint(String reglePoint) {
		this.reglePoint = reglePoint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "championnat")
	public Set<EquipeChampionnat> getEquipeChampionnats() {
		return this.equipeChampionnats;
	}

	public void setEquipeChampionnats(Set<EquipeChampionnat> equipeChampionnats) {
		this.equipeChampionnats = equipeChampionnats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "championnat")
	public Set<ResultatEpreuve> getResultatEpreuves() {
		return this.resultatEpreuves;
	}

	public void setResultatEpreuves(Set<ResultatEpreuve> resultatEpreuves) {
		this.resultatEpreuves = resultatEpreuves;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "championnat")
	public Set<ChampionnatCategorie> getChampionnatCategories() {
		return this.championnatCategories;
	}

	public void setChampionnatCategories(Set<ChampionnatCategorie> championnatCategories) {
		this.championnatCategories = championnatCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "championnat")
	public Set<ResultatChampionnat> getResultatChampionnats() {
		return this.resultatChampionnats;
	}

	public void setResultatChampionnats(Set<ResultatChampionnat> resultatChampionnats) {
		this.resultatChampionnats = resultatChampionnats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "championnat")
	public Set<Chapeau> getChapeaus() {
		return this.chapeaus;
	}

	public void setChapeaus(Set<Chapeau> chapeaus) {
		this.chapeaus = chapeaus;
	}

}
