package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapeau generated by hbm2java
 */
@Entity
@Table(name = "chapeau", catalog = "wrc")
public class Chapeau implements java.io.Serializable {

	private int id;
	private Championnat championnat;
	private String nom;
	private Set<ChapeauUtilisateur> chapeauUtilisateurs = new HashSet<ChapeauUtilisateur>(0);

	public Chapeau() {
	}

	public Chapeau(int id, Championnat championnat, String nom) {
		this.id = id;
		this.championnat = championnat;
		this.nom = nom;
	}

	public Chapeau(int id, Championnat championnat, String nom, Set<ChapeauUtilisateur> chapeauUtilisateurs) {
		this.id = id;
		this.championnat = championnat;
		this.nom = nom;
		this.chapeauUtilisateurs = chapeauUtilisateurs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChampionnat", nullable = false)
	public Championnat getChampionnat() {
		return this.championnat;
	}

	public void setChampionnat(Championnat championnat) {
		this.championnat = championnat;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chapeau")
	public Set<ChapeauUtilisateur> getChapeauUtilisateurs() {
		return this.chapeauUtilisateurs;
	}

	public void setChapeauUtilisateurs(Set<ChapeauUtilisateur> chapeauUtilisateurs) {
		this.chapeauUtilisateurs = chapeauUtilisateurs;
	}

}
