package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChapeauUtilisateur generated by hbm2java
 */
@Entity
@Table(name = "chapeau_utilisateur", catalog = "wrc")
public class ChapeauUtilisateur implements java.io.Serializable {

	private ChapeauUtilisateurId id;
	private Chapeau chapeau;
	private Utilisateur utilisateur;

	public ChapeauUtilisateur() {
	}

	public ChapeauUtilisateur(ChapeauUtilisateurId id) {
		this.id = id;
	}

	public ChapeauUtilisateur(ChapeauUtilisateurId id, Chapeau chapeau, Utilisateur utilisateur) {
		this.id = id;
		this.chapeau = chapeau;
		this.utilisateur = utilisateur;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idChapeau", column = @Column(name = "idChapeau")),
			@AttributeOverride(name = "idUtilisateur", column = @Column(name = "idUtilisateur")) })
	public ChapeauUtilisateurId getId() {
		return this.id;
	}

	public void setId(ChapeauUtilisateurId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChapeau", insertable = false, updatable = false)
	public Chapeau getChapeau() {
		return this.chapeau;
	}

	public void setChapeau(Chapeau chapeau) {
		this.chapeau = chapeau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur", insertable = false, updatable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

}
