package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChapeauUtilisateurId generated by hbm2java
 */
@Embeddable
public class ChapeauUtilisateurId implements java.io.Serializable {

	private Integer idChapeau;
	private Integer idUtilisateur;

	public ChapeauUtilisateurId() {
	}

	public ChapeauUtilisateurId(Integer idChapeau, Integer idUtilisateur) {
		this.idChapeau = idChapeau;
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "idChapeau")
	public Integer getIdChapeau() {
		return this.idChapeau;
	}

	public void setIdChapeau(Integer idChapeau) {
		this.idChapeau = idChapeau;
	}

	@Column(name = "idUtilisateur")
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChapeauUtilisateurId))
			return false;
		ChapeauUtilisateurId castOther = (ChapeauUtilisateurId) other;

		return ((this.getIdChapeau() == castOther.getIdChapeau()) || (this.getIdChapeau() != null
				&& castOther.getIdChapeau() != null && this.getIdChapeau().equals(castOther.getIdChapeau())))
				&& ((this.getIdUtilisateur() == castOther.getIdUtilisateur())
						|| (this.getIdUtilisateur() != null && castOther.getIdUtilisateur() != null
								&& this.getIdUtilisateur().equals(castOther.getIdUtilisateur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdChapeau() == null ? 0 : this.getIdChapeau().hashCode());
		result = 37 * result + (getIdUtilisateur() == null ? 0 : this.getIdUtilisateur().hashCode());
		return result;
	}

}
