package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EquipeChampionnat generated by hbm2java
 */
@Entity
@Table(name = "equipe_championnat", catalog = "wrc")
public class EquipeChampionnat implements java.io.Serializable {

	private int id;
	private Championnat championnat;
	private Vehicule vehicule;
	private String nom;

	public EquipeChampionnat() {
	}

	public EquipeChampionnat(int id) {
		this.id = id;
	}

	public EquipeChampionnat(int id, Championnat championnat, Vehicule vehicule, String nom) {
		this.id = id;
		this.championnat = championnat;
		this.vehicule = vehicule;
		this.nom = nom;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChampionnat")
	public Championnat getChampionnat() {
		return this.championnat;
	}

	public void setChampionnat(Championnat championnat) {
		this.championnat = championnat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVehicule")
	public Vehicule getVehicule() {
		return this.vehicule;
	}

	public void setVehicule(Vehicule vehicule) {
		this.vehicule = vehicule;
	}

	@Column(name = "nom", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
