package model;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamenSujet generated by hbm2java
 */
@Entity
//@Table(name = "examen_sujet", catalog = "u575564338_evaly")
@Table(name = "examen_sujet", catalog = "evaly")
public class ExamenSujet implements java.io.Serializable {

	private Integer idExamenSujet;
	private Examen examen;
	private Sujet sujet;

	public ExamenSujet() {
	}

	public ExamenSujet(Examen examen, Sujet sujet) {
		this.examen = examen;
		this.sujet = sujet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_examen_sujet", unique = true, nullable = false)
	public Integer getIdExamenSujet() {
		return this.idExamenSujet;
	}

	public void setIdExamenSujet(Integer idExamenSujet) {
		this.idExamenSujet = idExamenSujet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_examen")
	public Examen getExamen() {
		return this.examen;
	}

	public void setExamen(Examen examen) {
		this.examen = examen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sujet")
	public Sujet getSujet() {
		return this.sujet;
	}

	public void setSujet(Sujet sujet) {
		this.sujet = sujet;
	}

}