package model;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FormateurGroupeFormateur generated by hbm2java
 */
@Entity
@Table(name = "formateur_groupe_formateur", catalog = "evaly")
//@Table(name = "formateur_groupe_formateur", catalog = "u575564338_evaly")
public class FormateurGroupeFormateur implements java.io.Serializable {

	private Integer idFormateurGroupeFormateur;
	private Formateur formateur;
	private GroupeFormateur groupeFormateur;

	public FormateurGroupeFormateur() {
	}

	public FormateurGroupeFormateur(Formateur formateur, GroupeFormateur groupeFormateur) {
		this.formateur = formateur;
		this.groupeFormateur = groupeFormateur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_formateur_groupe_formateur", unique = true, nullable = false)
	public Integer getIdFormateurGroupeFormateur() {
		return this.idFormateurGroupeFormateur;
	}

	public void setIdFormateurGroupeFormateur(Integer idFormateurGroupeFormateur) {
		this.idFormateurGroupeFormateur = idFormateurGroupeFormateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formateur")
	public Formateur getFormateur() {
		return this.formateur;
	}

	public void setFormateur(Formateur formateur) {
		this.formateur = formateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe_formateur")
	public GroupeFormateur getGroupeFormateur() {
		return this.groupeFormateur;
	}

	public void setGroupeFormateur(GroupeFormateur groupeFormateur) {
		this.groupeFormateur = groupeFormateur;
	}

}