package model;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name = "organisation", catalog = "evaly")
//@Table(name = "organisation", catalog = "u575564338_evaly")
public class Organisation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idOrganisation;
	private String name;
	private Integer numero;
	private String rue;
	private String ville;
	private String code;
	
	private Set<GroupeFormateur> groupeFormateurs = new HashSet<GroupeFormateur>(0);
	private Set<Promotion> promotions = new HashSet<Promotion>(0);

	public Organisation() {
	}

	

	public Organisation(String name, Integer numero, String rue, String ville, String code,
			Set<GroupeFormateur> groupeFormateurs, Set<Promotion> promotions) {
		super();
		this.idOrganisation = idOrganisation;
		this.name = name;
		this.numero = numero;
		this.rue = rue;
		this.ville = ville;
		this.code = code;
		this.groupeFormateurs = groupeFormateurs;
		this.promotions = promotions;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_organisation", unique = true, nullable = false)
	public Integer getIdOrganisation() {
		return this.idOrganisation;
	}

	public void setIdOrganisation(Integer idOrganisation) {
		this.idOrganisation = idOrganisation;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<GroupeFormateur> getGroupeFormateurs() {
		return this.groupeFormateurs;
	}

	public void setGroupeFormateurs(Set<GroupeFormateur> groupeFormateurs) {
		this.groupeFormateurs = groupeFormateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Promotion> getPromotions() {
		return this.promotions;
	}

	public void setPromotions(Set<Promotion> promotions) {
		this.promotions = promotions;
	}

	public Integer getNumero() {
		return numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getRue() {
		return rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getVille() {
		return ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}