package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RallyeSpeciale generated by hbm2java
 */
@Entity
@Table(name = "rallye_speciale", catalog = "wrc")
public class RallyeSpeciale implements java.io.Serializable {

	private RallyeSpecialeId id;
	private Rallye rallye;
	private Speciale speciale;

	public RallyeSpeciale() {
	}

	public RallyeSpeciale(RallyeSpecialeId id) {
		this.id = id;
	}

	public RallyeSpeciale(RallyeSpecialeId id, Rallye rallye, Speciale speciale) {
		this.id = id;
		this.rallye = rallye;
		this.speciale = speciale;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idRallye", column = @Column(name = "idRallye")),
			@AttributeOverride(name = "idSpeciale", column = @Column(name = "idSpeciale")) })
	public RallyeSpecialeId getId() {
		return this.id;
	}

	public void setId(RallyeSpecialeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRallye", insertable = false, updatable = false)
	public Rallye getRallye() {
		return this.rallye;
	}

	public void setRallye(Rallye rallye) {
		this.rallye = rallye;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSpeciale", insertable = false, updatable = false)
	public Speciale getSpeciale() {
		return this.speciale;
	}

	public void setSpeciale(Speciale speciale) {
		this.speciale = speciale;
	}

}
