package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rallye generated by hbm2java
 */
@Entity
@Table(name = "rallye", catalog = "wrc")
public class Rallye implements java.io.Serializable {

	private int id;
	private String nom;
	private Set<RallyeSpeciale> rallyeSpeciales = new HashSet<RallyeSpeciale>(0);

	public Rallye() {
	}

	public Rallye(int id, String nom) {
		this.id = id;
		this.nom = nom;
	}

	public Rallye(int id, String nom, Set<RallyeSpeciale> rallyeSpeciales) {
		this.id = id;
		this.nom = nom;
		this.rallyeSpeciales = rallyeSpeciales;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rallye")
	public Set<RallyeSpeciale> getRallyeSpeciales() {
		return this.rallyeSpeciales;
	}

	public void setRallyeSpeciales(Set<RallyeSpeciale> rallyeSpeciales) {
		this.rallyeSpeciales = rallyeSpeciales;
	}

}
