package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RallyeSpecialeId generated by hbm2java
 */
@Embeddable
public class RallyeSpecialeId implements java.io.Serializable {

	private Integer idRallye;
	private Integer idSpeciale;

	public RallyeSpecialeId() {
	}

	public RallyeSpecialeId(Integer idRallye, Integer idSpeciale) {
		this.idRallye = idRallye;
		this.idSpeciale = idSpeciale;
	}

	@Column(name = "idRallye")
	public Integer getIdRallye() {
		return this.idRallye;
	}

	public void setIdRallye(Integer idRallye) {
		this.idRallye = idRallye;
	}

	@Column(name = "idSpeciale")
	public Integer getIdSpeciale() {
		return this.idSpeciale;
	}

	public void setIdSpeciale(Integer idSpeciale) {
		this.idSpeciale = idSpeciale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RallyeSpecialeId))
			return false;
		RallyeSpecialeId castOther = (RallyeSpecialeId) other;

		return ((this.getIdRallye() == castOther.getIdRallye()) || (this.getIdRallye() != null
				&& castOther.getIdRallye() != null && this.getIdRallye().equals(castOther.getIdRallye())))
				&& ((this.getIdSpeciale() == castOther.getIdSpeciale())
						|| (this.getIdSpeciale() != null && castOther.getIdSpeciale() != null
								&& this.getIdSpeciale().equals(castOther.getIdSpeciale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdRallye() == null ? 0 : this.getIdRallye().hashCode());
		result = 37 * result + (getIdSpeciale() == null ? 0 : this.getIdSpeciale().hashCode());
		return result;
	}

}
