package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ResultatSpeciale generated by hbm2java
 */
@Entity
@Table(name = "resultat_speciale", catalog = "wrc")
public class ResultatSpeciale implements java.io.Serializable {

	private int id;
	private Integer idUtilisateur;
	private String pseudo;
	private Integer temps;
	private Integer idEpreuveSpeciale;
	private Integer position;
	private Integer idChampionnat;
	private Integer points;

	public ResultatSpeciale() {
	}

	public ResultatSpeciale(int id) {
		this.id = id;
	}

	public ResultatSpeciale(int id, Integer idUtilisateur, String pseudo, Integer temps, Integer idEpreuveSpeciale,
			Integer position, Integer idChampionnat, Integer points) {
		this.id = id;
		this.idUtilisateur = idUtilisateur;
		this.pseudo = pseudo;
		this.temps = temps;
		this.idEpreuveSpeciale = idEpreuveSpeciale;
		this.position = position;
		this.idChampionnat = idChampionnat;
		this.points = points;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "idUtilisateur")
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "pseudo", length = 100)
	public String getPseudo() {
		return this.pseudo;
	}

	public void setPseudo(String pseudo) {
		this.pseudo = pseudo;
	}

	@Column(name = "temps")
	public Integer getTemps() {
		return this.temps;
	}

	public void setTemps(Integer temps) {
		this.temps = temps;
	}

	@Column(name = "idEpreuveSpeciale")
	public Integer getIdEpreuveSpeciale() {
		return this.idEpreuveSpeciale;
	}

	public void setIdEpreuveSpeciale(Integer idEpreuveSpeciale) {
		this.idEpreuveSpeciale = idEpreuveSpeciale;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "idChampionnat")
	public Integer getIdChampionnat() {
		return this.idChampionnat;
	}

	public void setIdChampionnat(Integer idChampionnat) {
		this.idChampionnat = idChampionnat;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

}
