package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResultatChampionnat generated by hbm2java
 */
@Entity
@Table(name = "resultat_championnat", catalog = "wrc")
public class ResultatChampionnat implements java.io.Serializable {

	private int id;
	private Championnat championnat;
	private Integer idUtilisateur;
	private String pseudo;
	private Integer temps;
	private Integer position;
	private Integer points;

	public ResultatChampionnat() {
	}

	public ResultatChampionnat(int id) {
		this.id = id;
	}

	public ResultatChampionnat(int id, Championnat championnat, Integer idUtilisateur, String pseudo, Integer temps,
			Integer position, Integer points) {
		this.id = id;
		this.championnat = championnat;
		this.idUtilisateur = idUtilisateur;
		this.pseudo = pseudo;
		this.temps = temps;
		this.position = position;
		this.points = points;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChampionnat")
	public Championnat getChampionnat() {
		return this.championnat;
	}

	public void setChampionnat(Championnat championnat) {
		this.championnat = championnat;
	}

	@Column(name = "idUtilisateur")
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "pseudo", length = 100)
	public String getPseudo() {
		return this.pseudo;
	}

	public void setPseudo(String pseudo) {
		this.pseudo = pseudo;
	}

	@Column(name = "temps")
	public Integer getTemps() {
		return this.temps;
	}

	public void setTemps(Integer temps) {
		this.temps = temps;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

}
