package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleUtilisateurId generated by hbm2java
 */
@Embeddable
public class RoleUtilisateurId implements java.io.Serializable {

	private int idUtilisateur;
	private int idRole;

	public RoleUtilisateurId() {
	}

	public RoleUtilisateurId(int idUtilisateur, int idRole) {
		this.idUtilisateur = idUtilisateur;
		this.idRole = idRole;
	}

	@Column(name = "id_utilisateur", nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "id_role", nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleUtilisateurId))
			return false;
		RoleUtilisateurId castOther = (RoleUtilisateurId) other;

		return (this.getIdUtilisateur() == castOther.getIdUtilisateur()) && (this.getIdRole() == castOther.getIdRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUtilisateur();
		result = 37 * result + this.getIdRole();
		return result;
	}

}
