package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleUtilisateur generated by hbm2java
 */
@Entity
@Table(name = "role_utilisateur", catalog = "wrc")
public class RoleUtilisateur implements java.io.Serializable {

	private RoleUtilisateurId id;
	private Role role;
	private Utilisateur utilisateur;

	public RoleUtilisateur() {
	}

	public RoleUtilisateur(RoleUtilisateurId id, Role role, Utilisateur utilisateur) {
		this.id = id;
		this.role = role;
		this.utilisateur = utilisateur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUtilisateur", column = @Column(name = "id_utilisateur", nullable = false)),
			@AttributeOverride(name = "idRole", column = @Column(name = "id_role", nullable = false)) })
	public RoleUtilisateurId getId() {
		return this.id;
	}

	public void setId(RoleUtilisateurId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_role", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur", nullable = false, insertable = false, updatable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

}
