package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "wrc")
public class Role implements java.io.Serializable {

	private Integer id;
	private String description;
	private String name;
	private Set<RoleUtilisateur> roleUtilisateurs = new HashSet<RoleUtilisateur>(0);

	public Role() {
	}

	public Role(String description, String name, Set<RoleUtilisateur> roleUtilisateurs) {
		this.description = description;
		this.name = name;
		this.roleUtilisateurs = roleUtilisateurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleUtilisateur> getRoleUtilisateurs() {
		return this.roleUtilisateurs;
	}

	public void setRoleUtilisateurs(Set<RoleUtilisateur> roleUtilisateurs) {
		this.roleUtilisateurs = roleUtilisateurs;
	}

}
