package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Speciale generated by hbm2java
 */
@Entity
@Table(name = "speciale", catalog = "wrc")
public class Speciale implements java.io.Serializable {

	private int id;
	private String nom;
	private double longueur;
	private Double denivele;
	private Set<EpreuveSpeciale> epreuveSpeciales = new HashSet<EpreuveSpeciale>(0);
	private Set<SpecialeSurface> specialeSurfaces = new HashSet<SpecialeSurface>(0);
	private Set<RallyeSpeciale> rallyeSpeciales = new HashSet<RallyeSpeciale>(0);

	public Speciale() {
	}

	public Speciale(int id, String nom, double longueur) {
		this.id = id;
		this.nom = nom;
		this.longueur = longueur;
	}

	public Speciale(int id, String nom, double longueur, Double denivele, Set<EpreuveSpeciale> epreuveSpeciales,
			Set<SpecialeSurface> specialeSurfaces, Set<RallyeSpeciale> rallyeSpeciales) {
		this.id = id;
		this.nom = nom;
		this.longueur = longueur;
		this.denivele = denivele;
		this.epreuveSpeciales = epreuveSpeciales;
		this.specialeSurfaces = specialeSurfaces;
		this.rallyeSpeciales = rallyeSpeciales;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "longueur", nullable = false, precision = 22, scale = 0)
	public double getLongueur() {
		return this.longueur;
	}

	public void setLongueur(double longueur) {
		this.longueur = longueur;
	}

	@Column(name = "denivele", precision = 22, scale = 0)
	public Double getDenivele() {
		return this.denivele;
	}

	public void setDenivele(Double denivele) {
		this.denivele = denivele;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "speciale")
	public Set<EpreuveSpeciale> getEpreuveSpeciales() {
		return this.epreuveSpeciales;
	}

	public void setEpreuveSpeciales(Set<EpreuveSpeciale> epreuveSpeciales) {
		this.epreuveSpeciales = epreuveSpeciales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "speciale")
	public Set<SpecialeSurface> getSpecialeSurfaces() {
		return this.specialeSurfaces;
	}

	public void setSpecialeSurfaces(Set<SpecialeSurface> specialeSurfaces) {
		this.specialeSurfaces = specialeSurfaces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "speciale")
	public Set<RallyeSpeciale> getRallyeSpeciales() {
		return this.rallyeSpeciales;
	}

	public void setRallyeSpeciales(Set<RallyeSpeciale> rallyeSpeciales) {
		this.rallyeSpeciales = rallyeSpeciales;
	}

}
