package model;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SujetQuestion generated by hbm2java
 */
@Entity
@Table(name = "sujet_question", catalog = "evaly")
//@Table(name = "sujet_question", catalog = "u575564338_evaly")
public class SujetQuestion implements java.io.Serializable {

	private Integer idSujetQuestion;
	private Question question;
	private Sujet sujet;

	public SujetQuestion() {
	}

	public SujetQuestion(Question question, Sujet sujet) {
		this.question = question;
		this.sujet = sujet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_sujet_question", unique = true, nullable = false)
	public Integer getIdSujetQuestion() {
		return this.idSujetQuestion;
	}

	public void setIdSujetQuestion(Integer idSujetQuestion) {
		this.idSujetQuestion = idSujetQuestion;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "id_question")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "id_sujet")
	public Sujet getSujet() {
		return this.sujet;
	}

	public void setSujet(Sujet sujet) {
		this.sujet = sujet;
	}

}