package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Surface generated by hbm2java
 */
@Entity
@Table(name = "surface", catalog = "wrc")
public class Surface implements java.io.Serializable {

	private int id;
	private String nom;
	private Set<SpecialeSurface> specialeSurfaces = new HashSet<SpecialeSurface>(0);

	public Surface() {
	}

	public Surface(int id) {
		this.id = id;
	}

	public Surface(int id, String nom, Set<SpecialeSurface> specialeSurfaces) {
		this.id = id;
		this.nom = nom;
		this.specialeSurfaces = specialeSurfaces;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surface")
	public Set<SpecialeSurface> getSpecialeSurfaces() {
		return this.specialeSurfaces;
	}

	public void setSpecialeSurfaces(Set<SpecialeSurface> specialeSurfaces) {
		this.specialeSurfaces = specialeSurfaces;
	}

}
