package model;
// Generated 10 mars 2024, 20:46:57 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name = "vehicule", catalog = "wrc")
public class Vehicule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -308305427515418731L;
	private int id;
	private Categorie categorie;
	private String nom;
	private Set<CategorieVehicule> categorieVehicules = new HashSet<CategorieVehicule>(0);
	private Set<EquipeChampionnat> equipeChampionnats = new HashSet<EquipeChampionnat>(0);

	public Vehicule() {
	}

	public Vehicule(int id) {
		this.id = id;
	}

	public Vehicule(int id, Categorie categorie, String nom, Set<CategorieVehicule> categorieVehicules,
			Set<EquipeChampionnat> equipeChampionnats) {
		this.id = id;
		this.categorie = categorie;
		this.nom = nom;
		this.categorieVehicules = categorieVehicules;
		this.equipeChampionnats = equipeChampionnats;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categorie")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicule")
	public Set<CategorieVehicule> getCategorieVehicules() {
		return this.categorieVehicules;
	}

	public void setCategorieVehicules(Set<CategorieVehicule> categorieVehicules) {
		this.categorieVehicules = categorieVehicules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicule")
	public Set<EquipeChampionnat> getEquipeChampionnats() {
		return this.equipeChampionnats;
	}

	public void setEquipeChampionnats(Set<EquipeChampionnat> equipeChampionnats) {
		this.equipeChampionnats = equipeChampionnats;
	}

}
